server:
  port: 9000 # 设置应用监听的端口

spring:
  application:
    name: learnService # 设置应用的名称

  datasource:
    url: jdbc:mysql://localhost:3306/mydb # 设置数据库连接URL
    username: root # 设置数据库用户名
    password: password # 设置数据库密码
    driver-class-name: com.mysql.cj.jdbc.Driver # 设置数据库驱动

logging:
  level:
    root: INFO # 设置根日志级别
    com.example.learn: DEBUG # 设置特定包的日志级别

# 配置 Spring Boot Actuator（健康检查等功能）
management:
  endpoints:
    web:
      exposure:
        include: health,info # 设置暴露的监控端点
  server:
    port: 8081 # 设置管理端口（可选）
